MVC/Controllers/EmpCRUDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using BO;
using MVC.Models;
using System.Data;

namespace MVC.Controllers
{
    public class EmpCRUDController : Controller
    {
        // GET: EmpCRUD
        public ActionResult Index()
        {
            DataTable dt = EmployeeDal.DisplayEmployee();
            return View(dt);
        }

        // GET: EmpCRUD/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EmpCRUD/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EmpCRUD/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: EmpCRUD/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: EmpCRUD/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: EmpCRUD/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: EmpCRUD/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //GET: EmpCRUD/MultipleDataReader
        public ActionResult MultipleReader()
        {
            empBO emp = EmployeeDal.DisplayEmployeesUsingDataReader();
            return View(emp);
        }

        //GET: EmpCRUD/DataAdapter
        public ActionResult DataAdapter()
        {
            DataTable dt = EmployeeDal.DisplayEmployeeUsingDataAdapter();
            return View(dt);
        }

        //GET: EmpCRUD/MultipleDataAdapter
        public ActionResult MultipleAdapter()
        {
            empBO emp = EmployeeDal.DisplayEmployeesUsingDataAdapter();
            return View(emp);
        }

        //Get: EmpCRUD/ScalarValue
        public ActionResult ScalarValue()
        {
            return View();
        }

        //Post: EmpCRUD/ScalarValue
        [HttpPost]
        public ActionResult ScalarValue(Employee emp)
        {
            int id = EmployeeDal.ScalarValue(emp);
            ViewBag.Message = "Scalar Value ID: " + id;
            return View();
        }

        // insert data into first table and get back the Primary Key from first table use that primary key as Foreign key to insert data into second table
        //Get: EmpCRUD/Tb1PKtoTb2FK
        public ActionResult Tb1PKtoTb2FK()
        {
            return View();
        }

        //POST: EmpCRUD/Tb1PKtoTb2FK
        [HttpPost]
        public ActionResult Tb1PKtoTb2FK(Tb1PKtoTb2FKBO insert)
        {
            EmployeeDal.InsertTables(insert);
            return RedirectToAction("Index");
        }

        //Get : EmpCRUD/FindName
        public ActionResult FindName()
        {
            return View();
        }

        //Post : EmpCRUD/FindName
        [HttpPost]
        public ActionResult FindName(Employee emp)
        {
            int id = EmployeeDal.FindName(emp);
            if (id > 0)
            {
                ViewBag.Message = "Name Exists";
            }
            else
            {
                ViewBag.Message = "Name does not Exists";
            }
            return View();
        }

        //Get: EmpCRUD/Multiple Records
        public ActionResult MultipleRecords()
        {
            return View();
        }

        //Post: EmpCRUD/Multiple Records
        [HttpPost]
        public ActionResult MultipleRecords(List<Employee> emp)
        {
            EmployeeDal.MultipleRecords(emp);
            return RedirectToAction("Index");
        }

        //Get: EmpCRUD/CustomTable
        public ActionResult CustomTable()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CustomTable(int id)
        {
            return View();
        }

        //Get: EmpCRUD/UserExistance
        public ActionResult UserExistance()
        {
            return View();
        }

        //POST: EmpCRUD/UserExistance
        [HttpPost]
        public ActionResult UserExistance(Employee emp)
        {
            Object obj = EmployeeDal.UserExistance(emp);

            if (obj is Employee)
            {
                ViewBag.message = "Name Exists";
                return View(obj);
            }
            else
            {
                ViewBag.Message = "Name does not Exists in Data Base";
            }
            return View();
        }

        // if user age is greater than 58
        //Get:EmpCRUD/DeleteAGE
        public ActionResult DeleteUser()
        {
            return View();
        }

        //Post: EmpCRUD/DeleteAge
        [HttpPost]
        public ActionResult DeleteUser(Employee emp)
        {
            EmployeeDal.DeleteUser(emp);
            return View();
        }

        public ActionResult DeleteAge()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DeleteAge(Employee emp)
        {
            EmployeeDal.DeleteAge(emp);
            return RedirectToAction("Index");
        }

        //Get: EmpCRUD/UpdateSalary
        public ActionResult UpdateSalary()
        {
            return View();
        }

        //Post: EmpCRUD/Updatesalary
        [HttpPost]
        [ActionName("UpdateSalary")]
        public ActionResult UpdateSal()
        {
            EmployeeDal.UpdateSalary();
            return RedirectToAction("Index");
        }
    }
}

MVC/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Models;
namespace MVC.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            EmpViewModel emp = new EmpViewModel();
            return View(emp);
        }

        public ActionResult GetEmployee()
        {

            return View();
        }

        [HttpPost]
        public ActionResult SaveEmployee(EmpViewModel model)
        {

            return View();
        }
    }
}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Q1", "Index", "Employee")</li>
                    <li>@Html.ActionLink("Q1b", "MultipleReader", "EmpCRUD")</li>
                    <li>@Html.ActionLink("Q2a", "DataAdapter", "EmpCRUD")</li>
                    <li>@Html.ActionLink("Q2b", "MultipleAdapter", "EmpCRUD")</li>
                    <li>@Html.ActionLink("Q3", "ScalarValue", "EmpCRUD")</li>
                    <li>@Html.ActionLink("Q4", "Tb1PKtoTb2FK", "EmpCRUD")</li>
                    <li>@Html.ActionLink("Q5", "FindName", "EmpCRUD")</li>
                    <li>@Html.ActionLink("Q6", "MultipleRecords", "EmpCRUD")</li>
                    <li>@Html.ActionLink("Q7", "CustomTable", "EmpCRUD")</li>
                    <li>@Html.ActionLink("Q8", "UserExistance", "EmpCRUD")</li>
                    <li>@Html.ActionLink("Q9", "DeleteUser", "EmpCRUD")</li>
                    <li>@Html.ActionLink("Q9b", "DeleteAge", "EmpCRUD")</li>
                    <li>@Html.ActionLink("Q10", "UpdateSalary", "EmpCRUD")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>